version: "3"
services:
  websocket:
    container_name: test-websocket-server
    build:
      dockerfile: Dockerfile
      context: docker/websocket
    volumes:
      - "./server:/home/app"
      # node_moduleを同期したくない場合は下記を追加
      # - "/home/app/node_modules"
    tty: true
    ports:
      - "${NODE_PORT:-3000}:${NODE_PORT:-3000}"
    working_dir: /home/app
    environment:
      - NODE_ENV=${NODE_ENV:-local}
      - NODE_PORT=${NODE_PORT:-3000}
      - TZ=${TZ:-Asia/Tokyo}

  nginx:
    container_name: test-websocket-nginx
    build:
      dockerfile: Dockerfile
      context: docker/nginx
    ports:
      - 443:443
    links:
      - 'websocket'
    depends_on:
      - websocket
    # SSLの場合は下記を追加
    # volumes:
    #   - "./docker/nginx/certs:/etc/nginx/cert"